project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - googled5e8d8be77b19177.html

website:
  title: "Chengxin-Michael Xu"
  search: false
  site-url: "https://cxuchengxin.github.io/chengxin-academic-site/"


  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd


    right:
      - text: 中文
        href: zh/
      - text: EN
        href: /

format:
  html:
    toc: false
    css: assets/css/styles.css