project:
  type: website
  output-dir: docs

website:
  title: "Chengxin-Michael Xu"
  search: false

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd


    right:
      - text: 中文
        href: zh/
      - text: EN
        href: /

format:
  html:
    toc: false
    css: assets/css/styles.css